# A comprehensive list of trusted domains to prevent false positives.
# This list includes approximately 500+ major global domains across all sectors.

TRUSTED_DOMAINS = {
    # SEARCH & TECH GIANTS
    "google.com", "google.co.uk", "google.co.in", "google.de", "google.fr", "google.co.jp",
    "bing.com", "yahoo.com", "duckduckgo.com", "baidu.com", "yandex.ru", "ask.com",
    "microsoft.com", "apple.com", "amazon.com", "amazon.co.uk", "amazon.de", "amazon.in",
    "meta.com", "facebook.com", "instagram.com", "whatsapp.com", "messenger.com",
    "twitter.com", "x.com", "linkedin.com", "github.com", "gitlab.com", "bitbucket.org",
    "adobe.com", "salesforce.com", "oracle.com", "sap.com", "ibm.com", "intel.com",
    "nvidia.com", "amd.com", "cisco.com", "hp.com", "dell.com", "lenovo.com",
    "vmware.com", "broadcom.com", "service-now.com", "atlassian.com", "jira.com",
    "slack.com", "zoom.us", "dropbox.com", "box.com", "wetransfer.com",
    "shopify.com", "squarespace.com", "wix.com", "wordpress.com", "wordpress.org",
    "cloudflare.com", "akamai.com", "fastly.com", "digitalocean.com", "heroku.com",
    "vercel.com", "netlify.com", "firebase.com", "mongodb.com", "redis.com",
    "elastic.co", "twilio.com", "stripe.com", "paypal.com", "adp.com", "workday.com",

    # SOCIAL, COMMUNICATION & COMMUNITY
    "reddit.com", "quora.com", "medium.com", "tumblr.com", "pinterest.com", "discord.com",
    "telegram.org", "signal.org", "snapchat.com", "tiktok.com", "weibo.com", "vk.com",
    "nextdoor.com", "meetup.com", "eventbrite.com", "vimeo.com", "flickr.com", "imgur.com",
    "stackexchange.com", "stackoverflow.com", "serverfault.com", "superuser.com",
    "behance.net", "dribbble.com", "deviantart.com", "artstation.com", "goodreads.com",

    # ENTERTAINMENT & STREAMING
    "netflix.com", "spotify.com", "youtube.com", "twitch.tv", "hulu.com", "disneyplus.com",
    "hbomax.com", "paramountplus.com", "peacocktv.com", "crunchyroll.com", "soundcloud.com",
    "pandora.com", "deezer.com", "tidal.com", "apple.co", "itunes.com", "bandcamp.com",
    "steampowered.com", "epicgames.com", "ubisoft.com", "ea.com", "nintendo.com",
    "playstation.com", "xbox.com", "roblox.com", "minecraft.net", "twitch.com",

    # FINANCIAL SERVICES & BANKING
    "visa.com", "mastercard.com", "americanexpress.com", "discover.com", "capitalone.com",
    "chase.com", "jpmorgan.com", "bankofamerica.com", "wellsfargo.com", "citibank.com",
    "citi.com", "usbank.com", "pnc.com", "goldmansachs.com", "morganstanley.com",
    "hsbc.com", "barclays.com", "standardchartered.com", "db.com", "bnpparibas.com",
    "fidelity.com", "vanguard.com", "schwab.com", "tdameritrade.com", "etrade.com",
    "robinhood.com", "coinbase.com", "binance.com", "kraken.com", "blockchain.com",
    "intuit.com", "turbotax.com", "quickbooks.com", "mint.com", "klarna.com", "affirm.com",

    # NEWS, MEDIA & PUBLISHING
    "bbc.com", "bbc.co.uk", "cnn.com", "nytimes.com", "washingtonpost.com", "theguardian.com",
    "reuters.com", "apnews.com", "bloomberg.com", "wsj.com", "forbes.com", "fortune.com",
    "economist.com", "time.com", "newsweek.com", "usatoday.com", "npr.org", "pbs.org",
    "aljazeera.com", "rt.com", "dw.com", "france24.com", "foxnews.com", "msnbc.com",
    "cnbc.com", "huffpost.com", "buzzfeed.com", "vice.com", "vox.com", "theverge.com",
    "wired.com", "techcrunch.com", "engadget.com", "gizmodo.com", "mashable.com",
    "cnet.com", "zdnet.com", "arstechnica.com", "nationalgeographic.com", "discovery.com",

    # SHOPPING & E-COMMERCE
    "ebay.com", "walmart.com", "target.com", "bestbuy.com", "homedepot.com", "lowes.com",
    "costco.com", "ikea.com", "macys.com", "nordstrom.com", "nike.com", "adidas.com",
    "zara.com", "h-m.com", "gap.com", "etsy.com", "alibaba.com", "aliexpress.com",
    "jd.com", "taobao.com", "rakuten.co.jp", "mercadolibre.com.ar", "daraz.pk",
    "flipkart.com", "myntra.com", "ajio.com", "nykaa.com", "meesho.com",

    # TRAVEL & TRANSPORTATION
    "uber.com", "lyft.com", "airbnb.com", "booking.com", "expedia.com", "tripadvisor.com",
    "kayak.com", "skyscanner.net", "hotels.com", "agoda.com", "zillow.com", "realtor.com",
    "tesla.com", "ford.com", "gm.com", "toyota.com", "honda.com", "bmw.com", "mercedes-benz.com",
    "delta.com", "united.com", "aa.com", "southwest.com", "lufthansa.com", "emirates.com",

    # EDUCATION, REFERENCE & GOVERNMENT
    "wikipedia.org", "wiktionary.org", "wikimedia.org", "britannica.com", "dictionary.com",
    "thesaurus.com", "merriam-webster.com", "oxfordlearnersdictionaries.com",
    "harvard.edu", "stanford.edu", "mit.edu", "berkeley.edu", "ox.ac.uk", "cam.ac.uk",
    "coursera.org", "udemy.com", "edx.org", "khanacademy.org", "duolingo.com",
    "nih.gov", "cdc.gov", "who.int", "un.org", "nasa.gov", "gov.uk", "canada.ca", "usa.gov",
    "irs.gov", "ssa.gov", "state.gov", "whitehouse.gov",

    # HEALTH & LIFESTYLE
    "webmd.com", "mayoclinic.org", "healthline.com", "medicalnewstoday.com",
    "allrecipes.com", "foodnetwork.com", "epicurious.com", "yelp.com", "tripadvisor.com",
    "weather.com", "accuweather.com", "wunderground.com", "noaa.gov",

    # GLOBAL BRANDS & MISC
    "cocacola.com", "pepsi.com", "nestle.com", "unilever.com", "pg.com", "johnsonandjohnson.com",
    "pfizer.com", "modernatx.com", "astrazeneca.com", "shell.com", "bp.com", "exxonmobil.com",
    "starbucks.com", "mcdonalds.com", "subway.com", "burgerking.com", "dominos.com",
    "fedex.com", "ups.com", "usps.com", "dhl.com", "maersk.com",

    # MORE TECH & UTILITIES
    "bitly.com", "tinyurl.com", "buffer.com", "hootsuite.com", "mailchimp.com", "sendgrid.com",
    "intercom.com", "zendesk.com", "hubspot.com", "canva.com", "figma.com", "invisionapp.com",
    "grammarly.com", "evernote.com", "notion.so", "trello.com", "asana.com", "monday.com",
    "teamviewer.com", "anydesk.com", "logmein.com", "parallels.com", "docker.com",
    "kubernetes.io", "terraform.io", "ansible.com", "jenkins.io", "circleci.com", "travis-ci.org",
    "mysql.com", "postgresql.org", "mariadb.org", "sqlite.org", "apache.org", "nginx.com",
    "python.org", "nodejs.org", "java.com", "oracle.com", "rust-lang.org", "golang.org",
    "php.net", "ruby-lang.org", "swift.org", "kotlinlang.org", "typescriptlang.org",
    "reactjs.org", "vuejs.org", "angular.io", "jquery.com", "getbootstrap.com", "tailwindcss.com",
    "fontawesome.com", "googlefonts.com", "fonts.google.com", "cdnjs.com", "unpkg.com", "jsdelivr.com",

    # ADDING HUNDREDS MORE DIVERSITY (SaaS, Regional, Specific Services)
    "lastpass.com", "1password.com", "dashlane.com", "bitwarden.com",
    "surveymonkey.com", "typeform.com", "jotform.com", "calendly.com",
    "docusign.com", "hellosign.com", "pandadoc.com",
    "shopify.in", "flipkart.com", "swiggy.com", "zomato.com", "ola.in", "paytm.com",
    "booking.com", "agoda.com", "expedia.com", "travelocity.com", "orbitz.com",
    "trip.com", "ctrip.com", "klook.com", "pelago.co",
    "shopee.com", "lazada.com", "tokopedia.com", "bukalapak.com", "grab.com", "gojek.com",
    "rakuten.com", "mercari.com", "line.me", "kakao.com", "naver.com", "daum.net",
    "tudou.com", "iqiyi.com", "youku.com", "bilibili.com",
    "globo.com", "uol.com.br", "terra.com.br", "estadao.com.br",
    "spiegel.de", "bild.de", "zeit.de", "faz.net",
    "lemonde.fr", "lefigaro.fr", "lequipe.fr",
    "elpais.com", "elmundo.es", "marca.com",
    "corriere.it", "repubblica.it", "gazzetta.it",
    "asahi.com", "yomiuri.co.jp", "nikkei.com",
    "thehindu.com", "timesofindia.indiatimes.com", "indianexpress.com", "ndtv.com",
    "alaskaair.com", "jetblue.com", "spirit.com", "frontierairlines.com",
    "ryanair.com", "easyjet.com", "britishairways.com", "airfrance.com", "klm.com",
    "ana.co.jp", "jal.co.jp", "cathaypacific.com", "singaporeair.com", "qantas.com",
    "marriott.com", "hilton.com", "hyatt.com", "ihg.com", "accor.com",
    "tripadvisor.co.uk", "tripadvisor.in", "yelp.co.uk",
    "glassdoor.com", "indeed.com", "monster.com", "ziprecruiter.com", "simplyhired.com",
    "craigslist.org", "gumtree.com", "olx.com", "avito.ru",
    "theatlantic.com", "newyorker.com", "rollingstone.com", "billboard.com", "variety.com",
    "hollywoodreporter.com", "deadline.com", "ign.com", "gamespot.com", "kotaku.com",
    "pcgamer.com", "polygon.com", "eurogamer.net", "rockpapershotgun.com",
    "nike.co.uk", "adidas.co.uk", "puma.com", "reebok.com", "underarmour.com", "newbalance.com",
    "sephora.com", "ulta.com", "loreal.com", "estee.com", "clinique.com",
    "ikea.com", "wayfair.com", "potterybarn.com", "westelm.com", "crateandbarrel.com",
    "bhphotovideo.com", "newegg.com", "microcenter.com", "tigerdirect.com",
    "autotrader.com", "cars.com", "edmunds.com", "kbb.com", "carmax.com",
    "weather.gov", "metoffice.gov.uk", "bom.gov.au",
    "who.int", "unicef.org", "redcross.org", "amnesty.org", "greenpeace.org",
    "nationalmssociety.org", "cancer.org", "heart.org", "diabetes.org",
    "nature.com", "sciencemag.org", "scientificamerican.com", "nasa.gov", "esa.int",
    "space.com", "phys.org", "sciencedaily.com",
    "cplusplus.com", "cppreference.com", "w3schools.com", "mozilla.org", "developer.mozilla.org",
    "geeksforgeeks.org", "tutorialspoint.com", "codecademy.com", "freecodecamp.org",
    "udacity.com", "pluralsight.com", "linkedin.com/learning",
    "web.archive.org", "archive.org", "scribd.com", "issuu.com", "slideshare.net",
    "prezi.com", "mentimeter.com", "slido.com", "kahoot.it",
    "canva.com", "picsart.com", "pixlr.com", "photopea.com", "unsplash.com", "pexels.com", "pixabay.com",
    "shutterstock.com", "gettyimages.com", "adobe.stock.com", "istockphoto.com",
    "envato.com", "themeforest.net", "codecanyon.net", "videohive.net", "audiojungle.net",
    "fiverr.com", "upwork.com", "toptal.com", "freelancer.com", "peopleperhour.com",
    "surveymonkey.com", "typeform.com", "google.com/forms", "microsoft.com/en-us/microsoft-365/online-surveys",
    "mailchimp.com", "constantcontact.com", "sendinblue.com", "mailerlite.com",
    "aweber.com", "getresponse.com", "convertkit.com", "activecampaign.com",
    "hubspot.com", "marketo.com", "pardot.com", "eloqua.com",
    "zendesk.com", "freshdesk.com", "intercom.com", "drift.com", "tawk.to",
    "shopify.com", "bigcommerce.com", "magento.com", "woocommerce.com", "prestashop.com",
    "ebates.com", "rakuten.com", "honey.com", "retailmenot.com", "coupons.com",
    "groupon.com", "livingsocial.com", "gilt.com", "ruelala.com",
    "zappos.com", "6pm.com", "overstock.com", "zulily.com",
    "chewy.com", "petsmart.com", "petco.com",
    "ticketmaster.com", "stubhub.com", "seatgeek.com", "vividseats.com",
    "fandango.com", "rottentomatoes.com", "metacritic.com", "imdb.com",
    "allmusic.com", "pitchfork.com", "nme.com", "rollingstone.com",
    "ted.com", "masterclass.com", "skillshare.com", "creativelive.com",
    "duolingo.com", "babbel.com", "rosettastone.com", "busuu.com",
    "grammarly.com", "hemingwayapp.com", "prowritingaid.com",
    "biblegateway.com", "bible.com", "quran.com", "chabad.org", "vatican.va",
    "ancestry.com", "23andme.com", "myheritage.com",
    "speedtest.net", "fast.com", "isitchaired.com", "downforeveryoneorjustme.com",
    "isitdownrightnow.com", "downdetector.com"
}
