"""subscription tiers

Revision ID: 65930f75f82a
Revises: 671ee040091c
Create Date: 2026-07-26 15:51:31.624824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65930f75f82a'
down_revision = '671ee040091c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.add_column('deletion_requests', sa.Column('user_email', sa.String(), nullable=True))
    op.execute(
        "UPDATE deletion_requests SET user_email = COALESCE("
        "(SELECT email FROM users WHERE users.id = deletion_requests.user_id), "
        "'deleted-user@phishx.com')"
    )
    op.alter_column('deletion_requests', 'user_email', nullable=False)
    op.add_column('deletion_requests', sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('deletion_requests', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('deletion_requests', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               nullable=True)
    op.create_index(op.f('ix_deletion_requests_user_email'), 'deletion_requests', ['user_email'], unique=False)
    op.drop_constraint('deletion_requests_user_id_fkey', 'deletion_requests', type_='foreignkey')
    op.create_foreign_key('fk_deletion_requests_user_id', 'deletion_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('deletion_requests', 'processed_at')
    op.alter_column('feedbacks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('feedbacks', 'scan_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('feedbacks', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('payments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('payments', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.add_column('scans', sa.Column('whois_data', sa.JSON(), nullable=True))
    op.alter_column('scans', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('scans', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.add_column('users', sa.Column('alert_preferences', sa.JSON(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'alert_preferences')
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('scans', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('scans', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('scans', 'whois_data')
    op.alter_column('payments', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('payments', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('feedbacks', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('feedbacks', 'scan_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('feedbacks', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('deletion_requests', sa.Column('processed_at', sa.DATETIME(), nullable=True))
    op.drop_constraint('fk_deletion_requests_user_id', 'deletion_requests', type_='foreignkey')
    op.create_foreign_key('deletion_requests_user_id_fkey', 'deletion_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_deletion_requests_user_email'), table_name='deletion_requests')
    op.alter_column('deletion_requests', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               nullable=False)
    op.alter_column('deletion_requests', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('deletion_requests', 'deleted_at')
    op.drop_column('deletion_requests', 'user_email')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
