"""add_subscription_fields

Revision ID: b40fb41a9f81
Revises: 0a11e8048c26
Create Date: 2026-07-28 22:10:51.024872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40fb41a9f81'
down_revision = '0a11e8048c26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.create_index('ix_users_rzp_sub_id', 'users', ['razorpay_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_rzp_sub_id', table_name='users')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'razorpay_subscription_id')
    with op.batch_alter_table('payments') as batch_op:
        batch_op.add_column(sa.Column('razorpay_signature', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index(op.f('ix_payments_razorpay_order_id'), ['razorpay_order_id'], unique=1)
    # ### end Alembic commands ###
