name: build-frontend

on:
  push:
  pull_request:

concurrency:
  group: build-frontend-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './phishx-frontend/package-lock.json'

      - name: Install Dependencies
        working-directory: ./phishx-frontend
        run: npm ci

      - name: Build Next.js App
        working-directory: ./phishx-frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
        run: npm run build
